name: Deploy to EC2

on:
  push:
    branches:
      - main # Or use a dedicated deploy branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd expediate_web || { echo "Directory expediate_web not found"; exit 1; }
            echo "Inside $(pwd)"
            git pull origin main
            npm install
            npm run build
            pm2 restart all || npm run start &
          EOF
